# Generated by Django 4.2 on 2023-04-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societe',
            name='siret',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
